# Generated by Django 3.2.5 on 2021-07-27 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('type_phone', models.CharField(choices=[('Celular', 'Celular'), ('House', 'House')], default='Celular', max_length=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactos.contact')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=15)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactos.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=15)),
                ('num_ext', models.CharField(max_length=15)),
                ('num_int', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=15)),
                ('province', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('CP', models.CharField(max_length=5)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactos.contact')),
            ],
        ),
    ]
