# Generated by Django 3.2.5 on 2021-07-28 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_rename_emailalternative_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='num_ext',
            new_name='outdoor_Number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='num_int',
        ),
    ]
