# Generated by Django 3.2.5 on 2021-07-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_auto_20210728_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type_address',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work')], default='Personal', max_length=10),
        ),
    ]
